version: '3.8'

services:
  amadeuscomic-app:
    build: ./app
    container_name: amadeuscomic_backend
    environment:
      - OHMYGPT_API_KEY=sk-CISjk5qJCF4e83C3181bT3BLbkFJ0573FB58E5E7403e905f
    volumes:
      - /app:/app
    restart: always
  nginx:
    image: nginx:latest
    container_name: amadeuscomic_nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - amadeuscomic-app
    restart: always
