version: '3.8'

services:
  comic-translate-web:
    build: ./app
    container_name: amadeuscomic_backend
    volumes:
      - /app:/app
    restart: always
#  nginx:
#    image: nginx:latest
#    container_name: amadeuscomic_nginx
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#      - ./nginx/certs:/etc/nginx/certs
#      - ./frontend:/usr/share/nginx/html
#    ports:
#      - "80:80"
#      - "443:443"
#    depends_on:
#      - amadeuscomic-app
#    restart: always
