api_base_url: ""
api_key: ""
detector_model: models/text_detector/comic-text-detector.onnx
font_dialogue: font_file/CN/SourceHanSansSC-Medium-2.otf
font_handwriting: font_file/CN/setofont.ttf
font_radiating: font_file/CN/special/SmileySans-Oblique.ttf
font_serious: font_file/CN/SourceHanSansSC-Medium-2.otf
font_narration: font_file/CN/special/LXGWWenKai-Regular.ttf
font_next_preview: font_file/CN/special/KleeOne-Regular.ttf
font_title: font_file/CN/SourceHanSansSC-Heavy-2.otf
font_size: 16
issue_url: ""
lama_model: models/manga-lama/lama-manga-dynamic.onnx
max_workers: null
multimodal: false
ocr_model: models/manga-ocr-onnx
page_input_dir: page/test
page_output_dir: page/output_page_output
page_test_output_dir: page/test_output
translation_model: gemini-2.5-flash
use_gpu: false
