api_base_url: https://api.n1n.ai/v1
api_key: sk-x8yZZ1BAI0NH6g7ofYdyTVSWWGZoG0LgFgz7PP2aY04FTCAv
detector_model: models/text_detector/comictextdetector.pt
font_dialogue: font_file/CN/SourceHanSerifCN-Regular-1.otf
font_handwriting: font_file/CN/setofont.ttf
font_radiating: font_file/CN/SourceHanSansSC-Heavy-2.otf
font_serious: font_file/CN/SourceHanSansSC-Medium-2.otf
font_size: 16
lama_model: models/manga-lama/manga-lama.pt
max_workers: null
page_input_dir: page/test_page
page_output_dir: page/test_page_output
translation_model: gemini-2.5-flash
use_gpu: false
