server {
    listen 443 ssl;
    server_name amadeuscomic.cn;

    ssl_certificate /etc/nginx/certs/amadeuscomic.cn.pem;
    ssl_certificate_key /etc/nginx/certs/amadeuscomic.cn.key;

    location / {
            root   /usr/share/nginx/html;
            index  index.html;
            try_files $uri $uri/ /index.html;
    }

    location /process-image {
            proxy_pass http://amadeuscomic-app:8000/process-image;
            proxy_buffering off;
            proxy_read_timeout 300s;	
    }
}
server {
    listen 80;
    server_name amadeuscomic.cn;
    return 301 https://$host$request_uri;
}










































